[package]
name = "lottery"
version = "0.3.0"
authors = ["Alexandre Duc <alexandre.duc@heig-vd.ch>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dryoc = "0.6"
read_input = "0.8"
hex = "0.4"
rand = "0.8"
